name: Docker Image CI for Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Habilita publicar imágenes en GHCR

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Build Angular project
        run: |
          npm run build --prod

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository_owner }}/cybergametime:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/cybergametimegateway-angular:latest
